# Generated by Django 4.1.5 on 2023-01-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_cont_comment_alter_cont_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
